### ISSUE TITLE
Moodle: Only 1 video is available in "My Series" and "Public Series" folder from PuMuKIT

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#16]
**Steps:**
- Select the Test PuMuKIT Integration course
- Click "Add an activity or resouce"
- In Resources select "Page" and press "Add"
- Fill in the name and in "Content" press the Media button (see picture below)
  ![media_button](https://cloud.githubusercontent.com/assets/19668673/16802904/5b4abf8e-4903-11e6-94fd-9188aaac526f.png)
- Click in "Browse repositories" and then PuMuKIT
- Click in Series >> My Series. There are two series. Click both to see the mm. obj. inside.
  ![undefine name](https://cloud.githubusercontent.com/assets/19668673/16802991/fccf9578-4903-11e6-99e8-1bda6eb54891.png)

**Result:**

There is only one video in both series, even though there is more than one multimedia object published on each series in PuMuKIT.

As shown in the previous picture, there is another issue with the name of the series and mm. obj. I will create a different issue.

**Comment by shermida** [comment]
@Alfro it happens the same in Public Series folder

**Comment by Alfro** [comment]
There you go.

**Comment by shermida** [comment]
Now it is possible to see all published videos in the series. The issue has been solved.
