### ISSUE TITLE
Moodle: PuMuKIT Repository: Show all playlist with published videos

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#18]
**Steps:**
- Select the Test PuMuKIT Integration course
- Click "Add an activity or resouce"
- In Resources select "Page" and press "Add"
- Fill in the name and in "Content" press the Media button (see picture below)
  ![media_button](https://cloud.githubusercontent.com/assets/19668673/16802904/5b4abf8e-4903-11e6-94fd-9188aaac526f.png)
- Click in "Browse repositories" and then PuMuKIT
- Click in Playlist >> My Playlist.
  ![all playlist](https://cloud.githubusercontent.com/assets/19668673/16808680/bf219680-491d-11e6-90f6-635733ef2390.png)

**Result:**

The user has only one playlist but many playlist are shown in the PuMuKIT Repository. These are the ones with at least one published video inside.

**Comment by Alfro** [comment]
There you go.

**Comment by shermida** [comment]
The issue has been solved.
