### ISSUE TITLE
Search option is not visible when a series or playlist is selected in pumukit integrated in moodle

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#19]
Steps:
- Log in in moodle
- Go to a course and activate edit mode
- Create a new unit. Select type "page"
- In the content of the page, click on media and after click in Browse Repositories
- Select pumukit repository  and then click on settings (gear icon)
- Click on any series or playlist

Problem: The search module is under the series or playlist preview, as you can see in the attached picture and you can not access to it.
![search_1](https://cloud.githubusercontent.com/assets/11191010/16809036/1b795584-491f-11e6-8ad0-e025ea977ae1.png)

**Comment by rubenrua** [comment]
https://github.com/campusdomar/PuMuKIT2/commit/be15a70167f20003d49fc0d3c688cf7389b67a41

**Comment by silviabf** [comment]
There are no preview and search modules now. I close this issue.
