### ISSUE TITLE
Tabs unselected when you select the videos in a playlist or series

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#20]
Steps:
- Enter in moodle repository
- Click on videos in any series or any playlist

Problem:
As you can see in the attached picture, the upper menu tabs are unselected and you do not know if you are into a playlist or into a series

![tabs](https://cloud.githubusercontent.com/assets/11191010/16810473/45c3bdca-4924-11e6-97f7-ef92076f33fe.png)

**Comment by Alfro** [comment]
This issue is out of the scope of this bundle:
Moved to campusdomar/PuMuKIT2#208
I am closing this issue.
