### ISSUE TITLE
Bad appearance of a window in groups avaliables section

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#21]
Steps:
- Enter in moodle repository
- Select any series
- In the series metadata option, select "Video Metadata Template"
- Click on "Owners & Groups"

Problem: As you can see in the attached picture, one of the window is down moved.

![add groups](https://cloud.githubusercontent.com/assets/11191010/16811449/b642f436-4928-11e6-9d0f-41431c7b3665.png)

**Comment by rubenrua** [comment]
https://github.com/campusdomar/PuMuKIT2/commit/cf2ea9fdba9f8be4f8d07486f8c61227eb2b03be?w=1

**Comment by silviabf** [comment]
This continues happening

**Comment by rubenrua** [comment]
``` diff
diff --git a/src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig b/src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig
index 02b49a2..0c750c7 100644
--- a/src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig
+++ b/src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig
@@ -645,7 +645,8 @@ hr.pumukit-green {
 }

 .pumukitnewadmin-groups-list-box {
-    width:375px;
+    max-width:375px;
+    width: 45%;
     height:220px;
     border: 1px solid #bbb;
     float: left;
@@ -659,7 +660,8 @@ hr.pumukit-green {
 }

 .list-box-width {
-    width:390px;
+    max-width:390px;
+    width: 40%;
 }
```

**Comment by Alfro** [comment]
@silviabf Added patch for groups variable width.

**Comment by silviabf** [comment]
Appearance is correct now. I close this issue.
