### ISSUE TITLE
The font color is so clear that it is hard to see new activity or resource in the course

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#24]
**Steps:**
- Select a course and turn editing on
- Add a Page resource 
- Fill in the mandatory fields and in "Description" add a video. Save it.
- Add another page resource but with text in the Description field and save it. 

**Result:**

As shown in the following picture, these resources have a color font so clear that it is difficult to see them.

_Edit:_ _Picture deleted_

**Comment by Alfro** [comment]
This issue is **_Out of Scope**_.
This depends on the particular _Theme_ a Moodle instalation has configured, it is not something we have control over on this bundle.
**Note:** I removed the picture.
