### ISSUE TITLE
You can not see all the categories in pumukit integrated in moodle

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#25]
Steps:
- Go to Moodle repository
- Click on videos in any series.
- Select categories tab in video metadata

Problem: As you can see in the attached picture, you can not see all the categories, only the firsts.

![categories](https://cloud.githubusercontent.com/assets/11191010/16833471/ce25d8fc-49af-11e6-91e6-b7a9e26b6fdc.png)

**Comment by Alfro** [comment]
I added a scroll on that part. It is not the best UX solution, but it should work well enough for now.

**Comment by silviabf** [comment]
I can see all the categories now. I close this issue.
