### ISSUE TITLE
Upload a video in publication channel "moodle" does not generate broadcast copy of the video

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#27]
Steps:
- Enter in Moodle repository ( This happens also if you do the same steps directly in pumukit)
- Click on any series
- Upload a video (with wizard option)
- In the publication channel select only moodle

Problem:
Pumukit processes the master copy, but it does not generate a broadcast copy, then, if you want to use the video in moodle you have to generate broadcast copy manually.

**Comment by Alfro** [comment]
Once the environment is set, you can try it again.

**Comment by silviabf** [comment]
Broadcast copy is generated now when mark moodle as publication channel. I close this issue.
