### ISSUE TITLE
Warning text overlapped in modify broadcast window

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#28]
Steps:
- Enter in Moodle repository
- Click on option icon of any series 
- Select "Modify all broadcast"

Problem:
As you can see in the attached picture, the text is overlapped.
![modify](https://cloud.githubusercontent.com/assets/11191010/16835363/abbfb2c0-49b8-11e6-9028-23e38431a8c3.png)

**Comment by Alfro** [comment]
Fixed with b2dbcc6

**Comment by Alfro** [comment]
@silviabf Take a look at it.

**Comment by silviabf** [comment]
Warning text is correct now. I close this issue.
