### ISSUE TITLE
Moodle Repository: Shows private videos without reason

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#31]
**Steps:**
- Add a page recource
- In the repository select "Public Series" and add these 4 vídeos with different brodcast (NOTE: The user is not added as an actor in none of them):
  ![broadcast_videos](https://cloud.githubusercontent.com/assets/19668673/16838984/b93aa4c8-49cc-11e6-9437-8dd3114078b8.png)
- Save and return to the course.
- Open the resorce in a Private Window in the Browser.

**Result:**
- It is possible to add videos with different broadcast and it shows the log in or the password request window:
  ![videos privados](https://cloud.githubusercontent.com/assets/19668673/16839078/61fcd11c-49cd-11e6-8fe8-0cab6b601e28.png)
- Video 1 (Broadcast Only Logged in Users): Click in Log in:
  ![logg in private video](https://cloud.githubusercontent.com/assets/19668673/16839096/7bd8beca-49cd-11e6-9d63-68035262b763.png)
- Video 2 (Broadcast Password Protected): Introduce a correct password: The video can be reproduced
- Video 3 and 4 (Broadcast Only Users in Groups): Click in Log in:
  ![logg in groups](https://cloud.githubusercontent.com/assets/19668673/16841558/0d97cba6-49da-11e6-9ea2-1ebe1d55d9eb.png)

**Comment by Alfro** [comment]
@shermida If the video is Public (that is, a video that is _listed_ in the WebTV Portal) then the expected result is to have it listed on the Moodle Repository as well.
If you cannot play a video (maybe you need a password), the expected result is that the player shows a form to insert it as well.

That is not a bug, it's the expected functionality

**Comment by shermida** [comment]
I misunderstood the user cases.
