### ISSUE TITLE
Playlist cannot be added in page resources in Moodle

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#33]
**Steps:**
- Create a new page resource in Moodle
- Click in Media icon and go to the Repository
- Click in PuMuKIT and select Playlist and then My Playlist folder
- Choose one playlist (for example "Prueba de playlist") and click Insert playlist.
- Click Select file

**Result:**

Error:
![playlist_cannot_be_added](https://cloud.githubusercontent.com/assets/19668673/16843677/85020870-49e2-11e6-9ae0-5a9e12f7ee0f.png)

**Comment by Alfro** [comment]
@shermida Fixed. Now playlists should be correctly added.

**Comment by shermida** [comment]
Playlists can be added. The issue has been solved.
