### ISSUE TITLE
Playlist with only one video published, do not show the video in the Repository

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#34]
**Steps:**
- With an Autopublisher user, create a new playlist with only one video published in WebTV
- In the Moodle Repository, open Playlist >> My Playlist and select the Playlist created before
- Click "Videos in this playlist"

**Result:** 

There is no videos in "Videos in this playlist" but there is one video in the Playlist:
![novideo](https://cloud.githubusercontent.com/assets/19668673/16844880/2d958936-49e7-11e6-81dd-4c8a4edbc932.png)

In PuMuKIT, add again the same video to the playlist.

Reload the Repository. Now it is possible to see both videos:
![videos_playlist](https://cloud.githubusercontent.com/assets/19668673/16844995/a4cb202e-49e7-11e6-9758-5819c3b1a07c.png)

**Comment by Alfro** [comment]
There.

**Comment by shermida** [comment]
The issue has been solved.
