### ISSUE TITLE
There is no title in the tab of the web browser

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-moodle-bundle#35]
Steps:
- Enter in Moodle repository
- **Click on Administration button**

Problem: As you can see in the attached picture, **there is no Tab Title in the Pumukit Management Window**
![url](https://cloud.githubusercontent.com/assets/11191010/16845632/e4a8aa5c-49e9-11e6-9739-dce37f716c8d.png)

**Comment by Alfro** [comment]
The block must be installed again.
Then this bug can be tested.

**Comment by silviabf** [comment]
Fixed. There is title now in the tab. I close this issue.
