### ISSUE TITLE
Moodle: Cloned objects do not appear listed on repository series 

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-moodle-bundle#36]
**Steps:**
- Upload Multimedia Object.
- Clone it and publish both of them on Moodle.
- Add both objects to a playlist.
- Go to Moodle Repository to see the playlist.

**Result:**
- The cloned Multimedia Object does not appear.

**Expected result:**
- All published objects on a playlist should appear.

**Comment by shermida** [comment]
All cloned videos are listed in the Moodle Repository.
