### ISSUE TITLE
Repository Search do not search Playlist names

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#37]
**Steps:**
- In PuMuKIT Series, create a new Series with _Nexus_ title 
- In PuMuKIT Playlist, create 2 playlist. One called _Nexus_ and another one called _Maths_
- Add videos to both playlist but with a title without the word Nexus on it
- Go to the Repository in Moodle and see these Playlist:
  ![playlistnexus](https://cloud.githubusercontent.com/assets/19668673/16846956/e22b01a8-49ee-11e6-8d28-74a72ddda5c5.png)
- Search the word Nexus in the Repository search:
  ![buscadorrepositorio](https://cloud.githubusercontent.com/assets/19668673/16847041/53a36d8e-49ef-11e6-81d3-65a642549b1a.png)

**Result 1:**

The Playlist with Nexus title has not been found, only the Series:
![search_nexus_playlist](https://cloud.githubusercontent.com/assets/19668673/16847063/6762f2a4-49ef-11e6-815a-b3dd6d5bec8b.png)

**Steps 2:**
- In PuMuKIT Series, create a new MO with title _Nexus_ in one Series
- In PuMuKIT Playlist, add the previous MO to the _Maths_ Playlist
- Go to the Repository in Moodle and search the word Nexus.

**Result 2:**

Again the Nexus Playlist has not been found only the MO inside the Maths Playlist:
![search_nexus](https://cloud.githubusercontent.com/assets/19668673/16847313/ad52f90c-49f0-11e6-9d7a-bb7512f00ac9.png)

**Expected Result:**

It should be possible to search playlist by its title.

**Comment by Alfro** [comment]
@shermida Take a look at it again

**Comment by shermida** [comment]
Now it is possible to search Playlists by title but there is a problem. 

**Steps:**
- Open the Moodle Repository:

![series_playlist](https://cloud.githubusercontent.com/assets/19668673/16875930/397bd03c-4aa2-11e6-9a8e-089d81a1cdc7.png)
- As shown in the picture above, there is a Series called Nexus and a Playlist called Nexus as well.
- Search _Nexus_ in the repository

**Result:**
- It has been found the _Nexus Series_, the _Nexus_ playlist, another playlist (_Maths_) with a video called Nexus but inside the Paylist folder there is now another folder called _Nexus Series_. 

![nexus_playlist](https://cloud.githubusercontent.com/assets/19668673/16875981/71ce746c-4aa2-11e6-895b-4ed1d27db5bc.png)
- _Nexus Series_ is a playlist now:

![serienexusplaylist](https://cloud.githubusercontent.com/assets/19668673/16876132/0e47ad36-4aa3-11e6-9d92-a1995b235b30.png)

**Expected Result:**

This Series should not be listed in Playlist.

**Comment by Alfro** [comment]
:open_mouth:

**Comment by Alfro** [comment]
:sweat:

**Comment by shermida** [comment]
Fixed.
