### ISSUE TITLE
Redundant way to delete a MO from a Playlist

### ISSUE THREAD

**Issue by shermida** [teltek/PuMuKIT2-moodle-bundle#43]
**Steps:**
- Click in Media Manager >> Playlist
- Select a Playlist and click Videos
- Select one MO from the list.

**Result:**

There are 3 ways to delete a MO and the 2 of them (the ones in the following picture) are redundant.

![delete_redundant](https://cloud.githubusercontent.com/assets/19668673/17025943/89fa27be-4f5e-11e6-96fb-03a9b3b165a4.png)

**Expected Result:**

Maybe it is better to remove one. If the hamburger icon can be useful in the future, the 'x' could be removed.

**Comment by rubenrua** [comment]
Fixed with https://github.com/campusdomar/PuMuKIT2/commit/775d638611de3d8db44f2cf0cfea33085820b147

**Comment by shermida** [comment]
Fixed
