### ISSUE TITLE
404 on /pumoodle route after installing

### ISSUE THREAD

**Issue by q0re** [teltek/PuMuKIT2-moodle-bundle#44]
I followed the installation guide to install pmk2-moodle-bundle and everything went fine. 
Composer installed the bundle right into the vendor folder, but the route /pumoodle is resulting in a 404. I checked the routing.yml file and everyhing looks fine. 

I have no idea what i am missing.
My routing.yml file:
```
pumukit_moodle:
    resource: "@PumukitMoodleBundle/Resources/config/routing.yml"
    prefix:   /
```
prod.log:
```
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /pumoodle" (from "http://**/pumoodle")" at /var/www/pumukit2/app/cache/prod/appProdUrlMatcher.php:2997)"} []
```

**Comment by Alfro** [comment]
@q0re Hi! Did you clear the cache?
Also, what is the return of this command:
```
php app/console debug:router  | grep pumukitmoodle
```

**Comment by Alfro** [comment]
@q0re Note. I hope you don't mind. I wrapped your snippets in code symbols (these: ` ``` `)

**Comment by q0re** [comment]
@Alfro Thanks, i cleared the cache, but still 404.
nothing is returned with grep.

**Comment by q0re** [comment]
`php app/console debug:router  | grep moodle` returns:

pumukit_moodle_moodle_index                         ANY             ANY    ANY  /pumoodle/index
 pumukit_moodle_moodle_repository                    ANY             ANY    ANY  /pumoodle/repository
 pumukit_moodle_moodle_embed                         ANY             ANY    ANY  /pumoodle/embed
 pumukit_moodle_embed_playlist                       ANY             ANY    ANY  /pumoodle/embed/playlist
 pumukit_moodle_moodle_metadata                      ANY             ANY    ANY  /pumoodle/metadata
 pumukit_moodle_repositorypmksearch_searchrepository ANY             ANY    ANY  /pumoodle/search_repository

**Comment by rubenrua** [comment]
@q0re, Could you run `php app/console debug:router --env=prod | grep noodle` to check an posibe issue with the Symfony cache?

**Comment by q0re** [comment]
@rubenrua same result:

 pumukit_moodle_moodle_index                         ANY             ANY    ANY  /pumoodle/index
 pumukit_moodle_moodle_repository                    ANY             ANY    ANY  /pumoodle/repository
 pumukit_moodle_moodle_embed                         ANY             ANY    ANY  /pumoodle/embed
 pumukit_moodle_embed_playlist                       ANY             ANY    ANY  /pumoodle/embed/playlist
 pumukit_moodle_moodle_metadata                      ANY             ANY    ANY  /pumoodle/metadata
 pumukit_moodle_repositorypmksearch_searchrepository ANY             ANY    ANY  /pumoodle/search_repository

I already cleared the cache with:
`php app/console cache:clear`
`php app/console cache:clear --env=prod`

**Comment by q0re** [comment]
It seems that its working now, oh wonder.. So maybe clearing the cache was the trick. 
Thanks everyone

**Comment by Alfro** [comment]
@q0re Glad to hear!
I'll close the issue then.
